apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-qwen
  namespace: default
  labels:
    app: vllm-qwen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vllm-qwen
  template:
    metadata:
      labels:
        app: vllm-qwen
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: g6e.12xlarge       # vram 48GB * GPU 4EA = 192 GB
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: vllm
          image: vllm/vllm-openai:latest
          command: ["python3", "-m", "vllm.entrypoints.openai.api_server"]
          args:
            - --model=Qwen/Qwen2.5-72B-Instruct    # fp16 사용시 134GB Weight 메모리 필요
            - --tensor-parallel-size=4             # g6e.12xlarge GPU 4장
            - --max-model-len=8192
            - --gpu-memory-utilization=0.90
            - --port=8000
            - --served-model-name=qwen
          ports:
            - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: "4"
            requests:
              nvidia.com/gpu: "4"
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
            - name: model-cache
              mountPath: /root/.cache/huggingface
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 120              # 파드 시작 후 120초 기다린 뒤 체크 시작
            periodSeconds: 10                     # 10초마다 /health 호출, readiness 체크가 성공해야 트래픽 받기 시작 (예들들어 120초 이상 넘어가서 150초 부터 트래픽을 받을 수 있음)
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 180              # 파드 시작 후 180초 기다린 뒤 체크 시작
            periodSeconds: 30                     # 30초마다 /health 호출, 실패하면 Kubernetes가 파드를 죽이고 재시작
      volumes:
        - name: shm
          emptyDir:
            medium: Memory                        # AWS 는 G 인스턴스 타입의 PCI 통신을 보안상으로 막아 놓았기 때문에 SHM 메모리 통신으로 fallback 된다. 그러므로 shared memory 사이즈를 좀 크게 잡아준다.
            sizeLimit: 16Gi                       # 통신 토폴로지 정보 (어떤 GPU가 어떤 경로로 연결됐는지), 동기화 플래그 (all-reduce 시작/완료 신호), 임시 버퍼 (작은 메시지 전달)
        - name: model-cache
          emptyDir: {}          # 프로덕션에서는 PVC 또는 S3 마운트 권장
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-qwen-svc
  namespace: default
spec:
  selector:
    app: vllm-qwen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
